[[redirects]]
  from = "/reservations"
  to = "https://tilat.lab.fi/getReservations.php"
  query = {room = ":room"}
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/buildings"
  to = "https://tilat.lab.fi/getRooms.php"
   query = {building = ":building"}
  status = 200
  force = true
  headers = {X-From = "Netlify"}  
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"