[[redirects]]
  from = "/reservations?room=:room"
  to = "https://tilat.lab.fi/getReservations.php"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/buildings?building=:building"
  to = "https://tilat.lab.fi/getRooms.php"
  status = 200
  force = true
  headers = {X-From = "Netlify"}  
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"