[[redirects]]
  from = "/reservations"
  to = "https://tilat.lab.fi/getReservations.php?room=2305"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"